In [16]:
import pandas as pd

data = pd.read_csv('dataframe.csv')

In [17]:
data.head()

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [18]:
data.rename(columns=
  {
    'Date' : 'Data',
    'Region' : 'Regiao',
    'Product Name' : 'Nome do Produto',
    'Units Sold' : 'Unidades Vendidas',
    'Unit Price' : 'Preco Unitario',
    'Total Revenue' : 'Receita Total',
    'Payment Method' : 'Metodo de Pagamento',
    'Product Category' : 'Categoria do Produto'

}, inplace = True
)

In [19]:
data['Receita Esperada'] = data['Unidades Vendidas'] * data['Preco Unitario']
data.head()

,Transaction ID,Data,Categoria do Produto,Nome do Produto,Unidades Vendidas,Preco Unitario,Receita Total,Regiao,Metodo de Pagamento,Receita Esperada
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal,499.99
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card,209.97
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal,89.99

In [20]:
qtd_credito = (data['Metodo de Pagamento'] == 'Credit Card').sum()
qtd_debit = (data['Metodo de Pagamento'] == 'Debit Card').sum()
qtd_paypal = (data['Metodo de Pagamento'] == 'PayPal').sum()

In [ ]:
qtd_creditodois = data.query('`Metodo de Pagamento` == "Credit Card"')sum()
qtd_creditodois

,Transaction ID,Data,Categoria do Produto,Nome do Produto,Unidades Vendidas,Preco Unitario,Receita Total,Regiao,Metodo de Pagamento,Receita Esperada
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card,1999.98
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card,63.96
5,10006,2024-01-06,Sports,Wilson Evolution Basketball,5,29.99,149.95,Asia,Credit Card,149.95
6,10007,2024-01-07,Electronics,MacBook Pro 16-inch,1,2499.99,2499.99,North America,Credit Card,2499.99
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card,51.98
...,...,...,...,...,...,...,...,...,...,...
231,10232,2024-08-19,Books,Dune by Frank Herbert,2,9.99,19.98,North America,Credit Card,19.98
233,10234,2024-08-21,Sports,Hydro Flask Standard Mouth Water Bottle,3,32.95,98.85,Asia,Credit Card,98.85
234,10235,2024-08-22,Electronics,Bose QuietComfort 35 II Wireless Headphones,1,299.00,299.00,North America,Credit Card,299.00
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card,32.97
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card,59.98

In [8]:
data_Pagamentos =  {
    'Cartao de Credito' : [qtd_credito],
    'Cartao de Debito' : [qtd_debit],
    'Paypal' : [qtd_paypal]
}

In [9]:
pagamento_por_regiao = data.groupby('Regiao')['Metodo de Pagamento'].value_counts()
pagamento_por_regiao

Regiao         Metodo de Pagamento
Asia           Credit Card            40
               Debit Card             40
Europe         PayPal                 80
North America  Credit Card            80
Name: count, dtype: int64